//Implement datatables
jQuery(document).ready(function() {
  jQuery('table.data_table').DataTable({
    paging: false
  });
});

//Implement toggle containers
jQuery(document).ready(function(){
  
  //  Summary: JQuery subroutine to support toggle containers
  //  Details: This script will first hide any elements with a 'toggleContiner' class. It will then find any elements with a class of 'toggleContinerTrigger', and attach a function to them which will toggle the following element (should be the toggleContainer) on or off when clicked.

  //Hide any elements with a 'toggleContainer' class
    jQuery(".toggleContainer").hide();
  //Attach a function to any elements with a class of 'toggleContinerTrigger', which will toggle the following element (should be the toggleContainer) on or off when clicked.
    jQuery(".toggleContainerTrigger").click(function(){
      jQuery(this).toggleClass("active").next().slideToggle("fast");
    });
});

//Implement qrcode stuff
jQuery(document).ready(function() {
  
  var qrcode = new QRCode(document.getElementById("qrcode"), {
    width : 100,
    height : 100
  });

  function makeCode () {    
    var elText = document.getElementById("text");
    
    if (!elText.value) {
      alert("Input a text");
      elText.focus();
      return;
    }
    
    qrcode.makeCode(elText.value);
  }

  makeCode();

  jQuery("#text").
  on("blur", function () {
    makeCode();
  }).
  on("keydown", function (e) {
    if (e.keyCode == 13) {
      makeCode();
    }
  });



  //Create output file button functionality
  jQuery("#createOutputFile").on("click",function(){
    //Create output file
      //var dataURL = document.getElementById('qrcode').toDataURL();
      var dataURL = document.querySelector('#qrcode canvas').toDataURL();

    //Output debugn info
      console.log(dataURL);

    //Set the download link href to a data URL generated by the makeOutputFile function, then make the link visible.
      jQuery("#downloadLink").attr("href",dataURL).css("display","inline");
  });


});

