//Implement datatables
jQuery(document).ready(function() {
  jQuery('table.data_table').DataTable({
    paging: false
  });
});

//Implement toggle containers
jQuery(document).ready(function(){
  
  //  Summary: JQuery subroutine to support toggle containers
  //  Details: This script will first hide any elements with a 'toggleContiner' class. It will then find any elements with a class of 'toggleContinerTrigger', and attach a function to them which will toggle the following element (should be the toggleContainer) on or off when clicked.

  //Hide any elements with a 'toggleContainer' class
    jQuery(".toggleContainer").hide();
  //Attach a function to any elements with a class of 'toggleContinerTrigger', which will toggle the following element (should be the toggleContainer) on or off when clicked.
    jQuery(".toggleContainerTrigger").click(function(){
      jQuery(this).toggleClass("active").next().slideToggle("fast");
    });
});

//Implement qrcode stuff
jQuery(document).ready(function() {

  //load QR codes on admin list
  //loop through the qr code output divs in the admin list
  jQuery.each(jQuery('.gmuw-sl-admin-list-qr-code'), function(index, value) {

    //get QR code-related elements for this record
    $my_qr_code_element=jQuery(this).children('.gmuw-sl-qr-code-output')[0];
    $my_qr_code_value=jQuery(this).children('.gmuw-sl-qr-code-value').val();
    $my_qr_code_download_link=jQuery(this).children('.gmuw-sl-qr-code-download')[0];

    //build QR code
    $my_qr_code = new QRCode($my_qr_code_element, {
      width : 100,
      height : 100
    });
    $my_qr_code.makeCode($my_qr_code_value);

    //set up download link
    //get new QR code canvas element
    $my_qr_code_canvas=jQuery($my_qr_code_element).children('canvas')[0];
    //build image data URL from canvas data
    $my_data_url = $my_qr_code_canvas.toDataURL();
    //set link href to image data URL
    jQuery($my_qr_code_download_link).attr("href",$my_data_url);
  });

  var qrcode = new QRCode(document.getElementById("qrcode"), {
    width : 100,
    height : 100
  });

  function makeCode () {    
    var elText = document.getElementById("text");
    
    if (!elText.value) {
      alert("Input a text");
      elText.focus();
      return;
    }
    
    qrcode.makeCode(elText.value);
  }

  makeCode();

  jQuery("#text").
  on("blur", function () {
    makeCode();
  }).
  on("keydown", function (e) {
    if (e.keyCode == 13) {
      makeCode();
    }
  });



  //Create output file button functionality
  jQuery("#createOutputFile").on("click",function(){
    //Create output file
      //var dataURL = document.getElementById('qrcode').toDataURL();
      var dataURL = document.querySelector('#qrcode canvas').toDataURL();

    //Output debugn info
      console.log(dataURL);

    //Set the download link href to a data URL generated by the makeOutputFile function, then make the link visible.
      jQuery("#downloadLink").attr("href",dataURL).css("display","inline");
  });


});

